### ISSUE TITLE
Maybe use something like `set_node_vars!`

### ISSUE THREAD

**Issue by ranocha** [trixi-gpu/TrixiCUDA.jl#2]
Consider

https://github.com/huiyuxie/trixi_cuda/blob/89270809378bde578906983555c3e8b6619d9882/cuda_dg_1d.jl#L85-L96

Here, you call 
```julia
u_node = get_nodes_vars(u, equations, j, k)
@inbounds flux_arr[i, j, k] = flux(u_node, 1, equations)[i]
```
for each `i in 1:size(u, 1)`. Thus, you compute the `flux` multiple times with the same argument if `nvariables(equations) > 1`. You could consider rewriting this such that you only "iterate" over the second and third dimension of `u`, compute the `flux(u_node, 1, equations)` only once, and write it to `flux_arr` in a small loop like
```julia
f = flux(u_node, 1, equations)
for i in axes(u, 1) # or 1:size(u, 1) or eachvariable(equations)
  @inbounds flux_arr[i, j, k] = f[i]
end
```

In Trixi.jl, we often use `set_node_vars!` as counterpart of `get_node_vars` for this.

The same applies to `surface_flux_kernel!` and `source_terms_kernel!`

**Comment by huiyuxie** [comment]
Thanks! I have created a new branch for performing benchmarks in the meeting.

**Comment by huiyuxie** [comment]
The mistake that caused three dimensional kernels faster than two dimensional kernels is, when changing from three to two, we should also change the corresponding `threadIdx().x`, `threadIdx().y`, and `threadIdx().z` etc. for `i`, `j`, and `k`. Take `flux_kernel!()` for example
```Julia
# Original 
function flux_kernel!(flux_arr, u, equations::AbstractEquations{1}, flux::Function)
    i = (blockIdx().x - 1) * blockDim().x + threadIdx().x
    j = (blockIdx().y - 1) * blockDim().y + threadIdx().y
    k = (blockIdx().z - 1) * blockDim().z + threadIdx().z
    ...
    return nothing
end
    
# Correct
function flux_kernel!(flux_arr, u, equations::AbstractEquations{1}, flux::Function)
    j = (blockIdx().x - 1) * blockDim().x + threadIdx().x
    k = (blockIdx().y - 1) * blockDim().y + threadIdx().y
    ...
    return nothing
end

# Incorrect
function flux_kernel!(flux_arr, u, equations::AbstractEquations{1}, flux::Function)
    j = (blockIdx().y - 1) * blockDim().y + threadIdx().y
    k = (blockIdx().z - 1) * blockDim().z + threadIdx().z
    ...
    return nothing
end
```
since the configurators always return the threads and blocks by order. See https://github.com/huiyuxie/trixi_cuda/blob/91f5331c95998b98c08488dfe5a0f6b1ae6bacab/cuda_dg_1d.jl#L8-L39
When we use the correct version of kernels, the benchmarks always showed that one dimensional kernels are better than two and two are better than three in time (when the range of index to be removed is rather small). So I reduced the kernel dimensions for the remaining kernel functions, including
https://github.com/huiyuxie/trixi_cuda/blob/91f5331c95998b98c08488dfe5a0f6b1ae6bacab/cuda_dg_1d.jl#L140
https://github.com/huiyuxie/trixi_cuda/blob/91f5331c95998b98c08488dfe5a0f6b1ae6bacab/cuda_dg_1d.jl#L174
https://github.com/huiyuxie/trixi_cuda/blob/91f5331c95998b98c08488dfe5a0f6b1ae6bacab/cuda_dg_1d.jl#L192
https://github.com/huiyuxie/trixi_cuda/blob/91f5331c95998b98c08488dfe5a0f6b1ae6bacab/cuda_dg_1d.jl#L238
and 
https://github.com/huiyuxie/trixi_cuda/blob/91f5331c95998b98c08488dfe5a0f6b1ae6bacab/cuda_dg_1d.jl#L291
Thank you so much for your valuable suggestions! I used to think that only 3D configurators could be applied but now all the configurators can be applied. Happy with that! Thanks!
