### ISSUE TITLE
Unify floating point types - and compare with CPU implementation

### ISSUE THREAD

**Issue by ranocha** [trixi-gpu/TrixiCUDA.jl#7]
The line

https://github.com/huiyuxie/trixi_cuda/blob/e2dd47f46f2d1d7c0dd6a6d657c2b4060ddbf7f1/example/example1.jl#L21

sets the type of the time `t` to `Float64` instead of `Float32`.

**Comment by huiyuxie** [comment]
For `example1.jl`, if I apply all the kernels in `rhs_cpu!()` here https://github.com/huiyuxie/trixi_cuda/blob/6b736229fdea3466f008e4b5edac2ddad1dc566f/cuda_dg_2d.jl#L622-L663
then the warning would disappear. 

Here are the results of running `extrema(sol_cpu.u[end] - sol_gpu.u[end])` for `example1.jl`, `example2.jl`, and `example3.jl`
```Julia
# Example 1
(-0.7075251034787967, 0.7075251034787917)

# Example 2
(-0.15977738342860448, 0.2807921957743247)

# Example 3
(-5.969505079228554e-5, 2.7934254639205847e-5)
```
It seems that only the result of the third example is acceptable. The first two are deviated too much so that I doubted there was something wrong with my code. 

But I checked the code again and further ran the same (similar) tests from here https://github.com/huiyuxie/trixi_cuda/blob/6b736229fdea3466f008e4b5edac2ddad1dc566f/cuda_dg_2d.jl#L5-L7 
using the initial data from `semidiscretize()` like 
https://github.com/huiyuxie/trixi_cuda/blob/6b736229fdea3466f008e4b5edac2ddad1dc566f/tests/advection_basic_2d.jl#L17-L21 for both branch `main` (Float32) and `type64` (Float64), the results of these raw implementation tests https://github.com/huiyuxie/trixi_cuda/blob/6b736229fdea3466f008e4b5edac2ddad1dc566f/cuda_dg_2d.jl#L740-L799 are definitely correct, see an example result of the test coming from `type64`
```Julia
julia> du1 - du2
4×4×4×256 StrideArray{Float64, 4, (1, 2, 3, 4), Tuple{StaticInt{4}, StaticInt{4}, StaticInt{4}, Int64}, NTuple{4, Nothing}, NTuple{4, StaticInt{1}}, Vector{Float64}} with indices static(1):static(4)×static(1):static(4)×static(1):static(4)×Base.OneTo(256):
[:, :, 1, 1] =
  0.0           0.0          2.84217e-14   2.84217e-14
 -5.68434e-14  -1.11022e-16  0.0          -1.42109e-14
  5.68434e-14  -1.11022e-16  5.68434e-14   4.26326e-14
 -8.52651e-14   0.0          0.0           0.0

[:, :, 2, 1] =
  0.0          -1.77636e-15  7.10543e-15  0.0
 -1.11022e-16  -1.77636e-15  0.0          5.69544e-14
  2.83107e-14   3.55271e-15  0.0          1.11022e-16
  5.68434e-14  -3.55271e-15  0.0          5.68434e-14

[:, :, 3, 1] =
  0.0          -7.10543e-15  0.0           0.0
  0.0           0.0          0.0           1.11022e-16
  0.0           0.0          7.10543e-15  -2.83107e-14
 -5.68434e-14   0.0          0.0           2.22045e-16

[:, :, 4, 1] =
  0.0          0.0           0.0          0.0
  1.42109e-14  1.11022e-16  -5.67324e-14  5.68434e-14
 -1.42109e-14  1.11022e-16   5.69544e-14  4.26326e-14
  0.0          5.68434e-14   5.70655e-14  0.0

[:, :, 1, 2] =
 0.0           0.0           5.68434e-14   2.84217e-14
 2.84217e-14   1.11022e-16   1.11022e-16   1.42109e-14
 7.10543e-14   1.11022e-16  -1.13576e-13  -4.26326e-14
 0.0          -5.68434e-14  -5.66214e-14   5.68434e-14

[:, :, 2, 2] =
  2.84217e-14  -1.77636e-15  1.77636e-15  0.0
  1.11022e-16   1.11022e-16  3.55271e-15  0.0
  1.11022e-16   1.11022e-16  0.0          2.84217e-14
 -1.13687e-13   2.22045e-16  3.55271e-15  0.0

[:, :, 3, 2] =
 0.0          0.0  5.55112e-17  2.77556e-17
 1.13798e-13  0.0  1.11022e-16  5.55112e-17
 1.11022e-16  0.0  1.11022e-16  5.55112e-17
 2.22045e-16  0.0  2.22045e-16  2.22045e-16

[:, :, 4, 2] =
  2.84217e-14  0.0          2.77556e-17  1.42109e-14
 -4.26326e-14  5.68434e-14  5.55112e-17  4.25771e-14
  1.42109e-14  0.0          5.55112e-17  5.67879e-14
  1.13687e-13  0.0          2.22045e-16  0.0

[:, :, 1, 3] =
 0.0           0.0           5.68434e-14   2.84217e-14
 2.84217e-14   1.11022e-16   1.11022e-16   1.42109e-14
 7.10543e-14   1.11022e-16  -1.13576e-13  -4.26326e-14
 0.0          -5.68434e-14  -5.66214e-14   5.68434e-14

[:, :, 2, 3] =
  2.84217e-14  -1.77636e-15  1.77636e-15  0.0
  1.11022e-16   1.11022e-16  3.55271e-15  0.0
  1.11022e-16   1.11022e-16  0.0          2.84217e-14
 -1.13687e-13   2.22045e-16  3.55271e-15  0.0

[:, :, 3, 3] =
 0.0          0.0  5.55112e-17  2.77556e-17
 1.13798e-13  0.0  1.11022e-16  5.55112e-17
 1.11022e-16  0.0  1.11022e-16  5.55112e-17
 2.22045e-16  0.0  2.22045e-16  2.22045e-16

[:, :, 4, 3] =
  2.84217e-14  0.0          2.77556e-17  1.42109e-14
 -4.26326e-14  5.68434e-14  5.55112e-17  4.25771e-14
  1.42109e-14  0.0          5.55112e-17  5.67879e-14
  1.13687e-13  0.0          2.22045e-16  0.0

;;;; … 

[:, :, 1, 254] =
 1.42109e-14  -2.84217e-14   0.0          -1.42109e-14
 1.42664e-14  -2.84772e-14   2.85327e-14   2.12053e-14
 1.42664e-14  -2.84772e-14  -5.67324e-14  -3.56382e-14
 2.84217e-14   0.0           0.0           0.0

[:, :, 2, 254] =
  0.0           1.77636e-15  -1.77636e-15   2.84217e-14
 -5.55112e-17  -1.77636e-15  -1.11022e-16   2.83107e-14
  2.83662e-14   3.55271e-15  -1.88738e-15  -1.11022e-16
  0.0           3.33067e-15   7.10543e-15  -2.22045e-16

[:, :, 3, 254] =
 2.84217e-14   0.0           0.0           0.0
 1.11022e-16  -1.11022e-16  -1.11022e-16  -5.69544e-14
 2.85327e-14   6.99441e-15  -1.11022e-16  -1.11022e-16
 0.0           0.0          -4.44089e-16   0.0

[:, :, 4, 254] =
  4.26326e-14   2.84217e-14   0.0          0.0
 -3.56382e-14  -2.85327e-14  -1.11022e-16  2.84217e-14
  2.12053e-14  -1.11022e-16   5.67324e-14  7.10543e-14
  0.0          -2.22045e-16   0.0          1.42109e-13

[:, :, 1, 255] =
 1.42109e-14  -2.84217e-14   0.0          -1.42109e-14
 1.42664e-14  -2.84772e-14   2.85327e-14   2.12053e-14
 1.42664e-14  -2.84772e-14  -5.67324e-14  -3.56382e-14
 2.84217e-14   0.0           0.0           0.0

[:, :, 2, 255] =
  0.0           1.77636e-15  -1.77636e-15   2.84217e-14
 -5.55112e-17  -1.77636e-15  -1.11022e-16   2.83107e-14
  2.83662e-14   3.55271e-15  -1.88738e-15  -1.11022e-16
  0.0           3.33067e-15   7.10543e-15  -2.22045e-16

[:, :, 3, 255] =
 2.84217e-14   0.0           0.0           0.0
 1.11022e-16  -1.11022e-16  -1.11022e-16  -5.69544e-14
 2.85327e-14   6.99441e-15  -1.11022e-16  -1.11022e-16
 0.0           0.0          -4.44089e-16   0.0

[:, :, 4, 255] =
  4.26326e-14   2.84217e-14   0.0          0.0
 -3.56382e-14  -2.85327e-14  -1.11022e-16  2.84217e-14
  2.12053e-14  -1.11022e-16   5.67324e-14  7.10543e-14
  0.0          -2.22045e-16   0.0          1.42109e-13

[:, :, 1, 256] =
  7.10543e-15  -2.84217e-14   0.0           0.0
 -3.56382e-14  -1.11022e-16  -1.11022e-16  -1.42109e-14
  2.83107e-14  -1.11022e-16  -1.11022e-16  -4.26326e-14
  0.0           5.66214e-14   0.0          -1.13687e-13

[:, :, 2, 256] =
  0.0           0.0          0.0           0.0
 -1.11022e-16  -1.77636e-15  1.77636e-15  -1.11022e-16
 -1.11022e-16  -3.55271e-15  0.0           2.83107e-14
 -2.22045e-16   0.0          3.55271e-15  -5.68434e-14

[:, :, 3, 256] =
  0.0          7.10543e-15  0.0   0.0
 -1.11022e-16  0.0          0.0   2.22045e-16
 -2.85327e-14  0.0          0.0  -2.81997e-14
 -5.68434e-14  0.0          0.0   0.0

[:, :, 4, 256] =
  0.0           0.0           0.0           0.0
 -1.42109e-14   2.83107e-14   2.22045e-16   0.0
  1.42109e-14  -1.11022e-16  -5.66214e-14   0.0
  5.68434e-14  -5.68434e-14   0.0          -2.84217e-14
```
```Julia
julia> maximum(abs.(du1 - du2))
2.2737367544323206e-13
```
The results of tests coming from `main` are weaker than `type64` in accuracy, but they are still acceptable. So I could say that there is no wrong in the part of my implementation.

**Comment by huiyuxie** [comment]
As for running this part from `example1.jl` (similar for `example2.jl` and `example3.jl`) https://github.com/huiyuxie/trixi_cuda/blob/6b736229fdea3466f008e4b5edac2ddad1dc566f/examples/example1.jl#L30-L32 
https://github.com/huiyuxie/trixi_cuda/blob/6b736229fdea3466f008e4b5edac2ddad1dc566f/examples/example1.jl#L61-L63 it will cause errors like 
```Julia
ERROR: MethodError: no method matching rhs!(::Vector{Float64}, ::Vector{Float64}, ::SemiHypMeshBCSolver{TreeMesh{2, SerialTree{2}}, BoundaryConditionPeriodic, DGSEM{LobattoLegendreBasis{Float64, 4, SVector{4, Float64}, Matrix{Float64}, Matrix{Float64}, Matrix{Float64}}, LobattoLegendreMortarL2{Float64, 4, Matrix{Float64}, Matrix{Float64}}, SurfaceIntegralWeakForm{FluxLaxFriedrichs{typeof(max_abs_speed_naive)}}, VolumeIntegralWeakForm}, LinearScalarAdvectionEquation2D{Float64}, typeof(initial_condition_convergence_test), Nothing, NamedTuple{(:elements, :interfaces, :boundaries, :mortars, :fstar_upper_threaded, :fstar_lower_threaded), Tuple{ElementContainer2D{Float64, Float64}, InterfaceContainer2D{Float64}, BoundaryContainer2D{Float64, Float64}, L2MortarContainer2D{Float64}, Vector{StaticArraysCore.MMatrix{1, 4, Float64, 4}}, Vector{StaticArraysCore.MMatrix{1, 4, Float64, 4}}}}}, ::Float64)

Closest candidates are:
  rhs!(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::BC, ::Source, ::Trixi.DGMulti{NDIMS, ElemType, var"#s2999", var"#s4308", var"#s4307", Mortar, <:RefElemData{NDIMS, ElemType, var"#s2999"}} where {var"#s2999"<:Polynomial{Gauss}, ElemType, NDIMS, var"#s4308"<:Trixi.SurfaceIntegralWeakForm, var"#s4307"<:Union{Trixi.VolumeIntegralFluxDifferencing, Trixi.VolumeIntegralShockCapturingHG}, Mortar}, ::Any) where {Source, BC}
   @ Trixi ~/.julia/packages/Trixi/IbRPV/src/solvers/dgmulti/flux_differencing_gauss_sbp.jl:509
  rhs!(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::BC, ::Source, ::Trixi.DGMulti{NDIMS, ElemType, ApproxType, var"#s4308", var"#s4307", Mortar, <:RefElemData{NDIMS, ElemType, ApproxType}} where {ElemType, NDIMS, ApproxType<:Union{SBP, AbstractDerivativeOperator}, var"#s4308"<:Trixi.SurfaceIntegralWeakForm, var"#s4307"<:Union{Trixi.VolumeIntegralFluxDifferencing, Trixi.VolumeIntegralShockCapturingHG}, Mortar}, ::Any) where {BC, Source}
   @ Trixi ~/.julia/packages/Trixi/IbRPV/src/solvers/dgmulti/flux_differencing.jl:614
  rhs!(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::BC, ::Source, ::Trixi.DGMulti{NDIMS, ElemType, ApproxType, var"#s4308", var"#s4307", Mortar, <:RefElemData{NDIMS, ElemType, ApproxType}} where {ApproxType, ElemType, NDIMS, var"#s4308"<:Trixi.SurfaceIntegralWeakForm, var"#s4307"<:Union{Trixi.VolumeIntegralFluxDifferencing, Trixi.VolumeIntegralShockCapturingHG}, Mortar}, ::Any) where {Source, BC}
   @ Trixi ~/.julia/packages/Trixi/IbRPV/src/solvers/dgmulti/flux_differencing.jl:578
  ...

Stacktrace:
 [1] top-level scope
   @ ~/trixi_cuda/examples/example1.jl:32
```

**Comment by huiyuxie** [comment]
Sorry I have no idea about why it works in the raw implementation but fails after being packed into `rhs!()`.
In order to figure out this issue, I think at least I have to know 1) how `OrdinaryDiffEq.solve()` deals with `du` and `u` via `rhs!()` function and 2) how parameter like `RDPK3SpFSAL49()` etc. works. But now I just have no idea.

**Comment by ranocha** [comment]
When we call `ode = semidiscretize(semi, tspan)`, we set up an `ODEProblem` from OrdinaryDiffEq.jl. For this, we first compute the coefficients of the initial condition in
https://github.com/trixi-framework/Trixi.jl/blob/53a826b62241fc0f58c0a3cd0a0acc1789a79509/src/semidiscretization/semidiscretization.jl#L82
and create the corresponding `ODEProblem` in
https://github.com/trixi-framework/Trixi.jl/blob/53a826b62241fc0f58c0a3cd0a0acc1789a79509/src/semidiscretization/semidiscretization.jl#L88C66-L88C66
It is set up to use our `Trixi.rhs!` as the ODE right-hand side determining the time derivative.

In OrdinaryDiffEq.jl, calling `solve` leads to a time integration loop. One step for the algorithm you mentioned above is defined in
https://github.com/SciML/OrdinaryDiffEq.jl/blob/3bba7679a275cb2ecb1af666a754d49b850c4459/src/perform_step/low_storage_rk_perform_step.jl#L266-L302
There, `p` is our semidiscretization `semi`, `u` is our `u_ode`, and `du` is what we call `du_ode` in Trixi.jl.

**Comment by ranocha** [comment]
You could try
- other time integration methods like `BS3()` or `Tsit5()`
- fixed time step sizes by passing `adaptive = false, dt = some_time_step_size_that_is_small_enough` to `solve` as keyword arguments
- to look at the time integration process step by step

For the last approach, you can initialize an ODE integrator as
```julia
integrator = init(ode, ...)
```
instead of calling
```julia
sol = solve(ode, ...)
```
Then, you can perform one time step by calling
```julia
step!(integrator)
```
You can inspect 
- the current solution `integrator.u`,
- the current time `integrator.t`
- the current time step size `integrator.dt`

and see where the differences come from.
See also https://docs.sciml.ai/DiffEqDocs/stable/basics/integrator/

**Comment by huiyuxie** [comment]
Thanks for your reply! I will try what you suggested and update them later here.

**Comment by huiyuxie** [comment]
> Other time integration methods like `BS3()` or `Tsit5()`

The results of `extrema(sol_cpu.u[end] - sol_gpu.u[end])` are almost the same for these three examples, like below
```Julia
# `BS3()` for example 1
(-0.7075268104564877, 0.7075268751976517)
# `Tsit5()` for example 1
(-0.7075284610182293, 0.7075285257425542)

# `BS3()` for example 2
(-0.15900264751233806, 0.2771948607762127)
#  `Tsit5()` for example 2
(-0.15904315725630624, 0.27707899666396685)

# `BS3()` for example 3
(-5.992841043767072e-5, 4.0195123097941376e-5)
# `Tsit5()` for example 3
(-4.856290201704638e-5, 3.6227811167410806e-5)
```

**Comment by huiyuxie** [comment]
Similar for 

> Fixed time step sizes by passing adaptive = false, dt = some_time_step_size_that_is_small_enough to solve as keyword arguments

```Julia
# `BS3(), adaptive=false, dt=0.01` for example 1
(-0.707527725595977, 0.7075277903255727)
 # `Tsit5(), adaptive=false, dt=0.01` for example 1
(-0.707527803913327, 0.7075278686422818)

# `BS3(), adaptive=false, dt=0.01` for example 2
(-0.15904403780456278, 0.27709502086661075)
 # `Tsit5(), adaptive=false, dt=0.01` for example 2
(-0.15904728701467263, 0.27707896550769817)
```

**Comment by huiyuxie** [comment]
To summarize, 

> Look at the time integration process step by step

These are what I tried for both `Float32` and `Float64` (like for `example1.jl`) https://github.com/huiyuxie/trixi_cuda/blob/5b52e0868a0b985dc70fc23168dd3919d454bf7b/examples/example1.jl#L69-L86 

The results showed that both `Float32` and `Float64` began to deviate from true values (CPU values) from step 4. For more details, see (I omit both `integrator_cpu.u` and `integrator_gpu.u` since they are too long)
```Julia
# For `main` branch
Step:4
CPU: [..] 0.15809316885652322 0.061322101745377694
GPU: [..] 0.001111 0.0009999999

Step:5
CPU: [..] 0.23943041625686362 0.08133724740034042
GPU: [..] 0.011111 0.01

Step:6
CPU: [..] 0.336277708599257 0.09684729234239334
GPU: [..] 0.11111099 0.099999994

Step:7
CPU: [..] 0.4520607965859968 0.11578308798673981
GPU: [..] 1.0 0.888889
```
```Julia
# For `type64` branch
Step:4
CPU: [..] 0.1580932402085946 0.06132212497551236
GPU: [..] 0.001111 0.0009999999

Step:5
CPU: [..] 0.23943057558094133 0.08133733537234672
GPU: [..] 0.011111 0.01

Step:6
CPU: [..] 0.3362778733894814 0.09684729780854007
GPU: [..] 0.11111099 0.099999994

Step:7
CPU: [..] 0.45206094040929407 0.11578306701981268
GPU: [..] 1.0 0.888889
```
Based on the above, the GPU version of `integrator.dt` becomes large immediately at the final step, leading to its `integrator.t` increases slowly at first but rapidly at the end. Also, the values of `integrator.dt` and `integrator.t` even did not change at all. So I suspect that the problem maybe come from the `rhs_gpu!()` that it may not change the values of `du` successfully after packing those kernels inside.

**Comment by huiyuxie** [comment]
Wow, that is so funny! It really failed to update the value of `du`, see if I ran 
```Julia
du1 = du
rhs_gpu!(du, u, t, mesh, equations, initial_condition, boundary_conditions, source_terms, solver, cache)
du2 = du
```
and then `du1 - du2` would give me all zeros. Something like this happened before when I tried to prototype kernels `copy_to_gpu!()` and `copy_to_cpu!()` so that's why I used `du, u = ...` https://github.com/huiyuxie/trixi_cuda/blob/f0811dfaedf7ba03982007889b45e0ffe415885f/cuda_dg_2d.jl#L686-L719 here. If not, then the values of `du` would not change after running these two kernels. So I think if in some way like changing the `du` to a global variable in the whole process it may help, or use something like `du, u = ...` here 
https://github.com/huiyuxie/trixi_cuda/blob/f0811dfaedf7ba03982007889b45e0ffe415885f/cuda_dg_2d.jl#L727C5-L727C24.

**Comment by huiyuxie** [comment]
I tried something like `du, u = ...` here https://github.com/huiyuxie/trixi_cuda/blob/8145d63632a218ec4d0c264f96288d76f1408bbd/cuda_dg_2d.jl#L686-L719 and here https://github.com/huiyuxie/trixi_cuda/blob/8145d63632a218ec4d0c264f96288d76f1408bbd/cuda_dg_2d.jl#L721-L730 but it still seemed that the `du` values did not update through `rhs_gpu!()`. The point is that I'm not sure about how ODE package deals with `du` and `u`, like if they do something like `rhs!(du, u, semi, t); u .= u .+ dt .* du; rhs!(du, u, semi, t); u .= u .+ dt .* du; #continue` instead of `du, u = rhs!(du, u, semi, t); u .= u .+ dt .* du; du, u = rhs!(du, u, semi, t); u .= u .+ dt .* du; #continue` inherently then there seems no way for us to fix this. 

Also, I'm still wired about why `du` values cannot be updated through `rhs_gpu!()`, but it can be updated with success in raw implementation (i.e. without packing kernels into `rhs_gpu!()`).
